shop/product/urls.py
from django.conf.urls import include, url
from .import views

urlpatterns = [
        url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
        url(r'^all/$', views.category, name='category_all' )

]

shop/shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^product/', include('product.urls', namespace="product" )),
    url(r'^$', views.home, name='home'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/product/models.py
from django.db import models
from django.core.urlresolvers import reverse



class Category(models.Model):
    name = models.CharField(max_length=199,db_index = True)
    slug = models.SlugField(max_length=200,db_index = True,unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name




class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products')
    name = models.CharField(max_length=199, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description  = models.TextField(blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ("name",)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('product:product_detail',
                       args=[self.id, self.slug])

shop/product/views.py
from django.shortcuts import render,get_object_or_404

from .import models

def product_detail(request, id, slug):
    product = models.Product.objects.get(id=id,slug=slug)
    return render(request,'product/detail.html', {'product' : product})

def category(request):
    category = models.Category.objects.all()
    products = models.Product.objects.all()
    return render(request, 'product/category.html', {'categorys' : category, 'product': products  })

# Create your views here.

shop/shop/views.py
from django.shortcuts import render
from product.models import Product


def home(request):
    product = Product.objects.all()
    return render(request, 'home.html', {'Prodycts': product} )

shop/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Магазин</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Eda Shop.ru</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href=" {% url 'product:category_all' %}">все товары<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Категории
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">

            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Поисковик" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
        </form>
      </div>
    </nav>


    {% block content %}
    {% endblock %}

    <!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <section
    class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
  >
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Contact
          </h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/home.html
{% extends "base.html" %}
{% load static %}
    {% block content %}
<h1 style="text-align:center">Новое</h1>
    <div class="container">
      <div class="row">
    {% for product in Prodycts%}
        <div class="card col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3"   >
          <img src=" {{ product.image.url  }} " class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title" style="text-align:center">{{product.name}}</h5>
            <p class="card-text"  style="text-align:center">{{product.description}}</p>
          </div>
            <p style="text-align:center"> {{product.price}} Р </p>
          <div class="card-body">
            <a href="#" class="card-link">Добавить в корзину</a>
            <a href="#" class="card-link">Подробнее</a>
          </div>
        </div>
    {% endfor %}
          </div>
          </div>
    {% endblock %}

shop/templates/menu.html
{% for i in category %}
              <a class="dropdown-item" href="#">{{i}}</a>
{% endfor %}

shop/templates/product/category.html
{% extends "base.html" %}
{% load static %}
    {% block content %}
<h1 style="text-align:center">Категории</h1>
    <div class="container-category">
      <div class="row justify-content-center">
    {% for category in categorys %}
        <div class="card col-11 col-sm-11 col-md-5 col-lg-2 col-xl-2"   >
          <div class="card-body">
            <h5 class="card-title" style="text-align:center">{{category.name}}</h5>
            <p class="card-text"  style="text-align:center">{{category.description}}</p>
          </div>
          <div class="card-body">
            <a href="#" class="card-link">Товары этой категории</a>
          </div>
        </div>
    {% endfor %}
          </div>
          </div>
{% for i in product %}
            <h5 class="card-title" style="text-align:center">{{i.name}}</h5>
            <p class="card-text"  style="text-align:center">{{i.description}}</p>
{% endfor %}
    {% endblock %}

shop/templates/product/detail.html
{% extends "base.html" %}
{% load static %}
    {% block content %}
  <div class="container">
      <div class="row justify-content-center">
        <div class="card col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3"   >
          <img src=" {{ product.image.url  }} " class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title" style="text-align:center">{{product.name}}</h5>
            <p class="card-text"  style="text-align:center">{{product.description}}</p>
          </div>
            <p style="text-align:center"> {{product.price}} Р </p>
          <div class="card-body">
            <a href="#" class="card-link">Добавить в корзину</a>
          </div>
        </div>
          </div>
          </div>
    {% endblock %}